# Generated by Django 4.2.5 on 2023-11-20 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import timezone_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SmtpModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('smtp_server', models.CharField(max_length=255)),
                ('port', models.PositiveIntegerField()),
                ('imap_server', models.CharField(max_length=255)),
                ('imap_port', models.PositiveIntegerField()),
                ('app_password', models.CharField(max_length=128)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LeadList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_name', models.CharField(max_length=255)),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LeadEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=225)),
                ('role', models.CharField(max_length=225)),
                ('column_f', models.CharField(max_length=500)),
                ('column_g', models.CharField(max_length=500)),
                ('column_h', models.CharField(max_length=500)),
                ('column_i', models.CharField(max_length=500)),
                ('column_j', models.CharField(max_length=500)),
                ('lead_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_app.leadlist')),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_running', models.BooleanField(default=False)),
                ('timezone', timezone_field.fields.TimeZoneField(default='CST')),
                ('daily_limit', models.PositiveIntegerField()),
                ('lead_list', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard_app.leadlist')),
                ('sender_email', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard_app.smtpmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
