# Generated by Django 4.2.5 on 2023-10-26 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0004_rename_smtpdata_smtpmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smtpmodel',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
    ]
