# Generated by Django 4.2.5 on 2023-10-26 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0005_alter_smtpmodel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smtpmodel',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
