# Generated by Django 4.2.5 on 2023-10-05 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
