# Generated by Django 4.2.5 on 2023-10-26 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite_app', '0002_userlimits'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountLimits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtp_limit', models.PositiveIntegerField(default=1)),
                ('sending_limit', models.PositiveIntegerField(default=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UserLimits',
        ),
    ]
