# Generated by Django 4.2.5 on 2023-10-26 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite_app', '0003_accountlimits_delete_userlimits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountlimits',
            name='sending_limit',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
