# Generated by Django 4.2.5 on 2023-10-26 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite_app', '0004_alter_accountlimits_sending_limit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccountLimits',
            new_name='AccountLimit',
        ),
    ]
